apiVersion: apps/v1
kind: Deployment
metadata: { name: nimbus-frontend }
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector: { matchLabels: { app: nimbus-frontend } }
  template:
    metadata: { labels: { app: nimbus-frontend } }
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}"
          ports: [{ containerPort: 80 }]
