apiVersion: v1
kind: Service
metadata: 
  name: nimbus-backend
spec:
  type: NodePort
  selector: 
    app: nimbus-backend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30400
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
  name: nimbus-frontend
spec:
  type: NodePort
  selector: 
    app: nimbus-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30401
      protocol: TCP
